name: geocoder_example
description: Demonstrates how to use the geocoder plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  geocoder:
    path: ../

flutter:
  uses-material-design: true